### ISSUE TITLE
Share directly to ios app not via middle prompt 

### ISSUE THREAD

**Issue by j-d-carmichael** [carsten-klaffke/send-intent#13]
Is it possible with this plugin to be able to share directly to the app without having to 1st go through the ios middle ground popup?

For example, like in the gmail app the shared content just gets passed straight through to the app.

ios 14.7.1
xcode 12.5.1
latest capacitorjs with the recent and latest updated code to this plugin

**Comment by Saqib92** [comment]
any update?

**Comment by j-d-carmichael** [comment]
Ah sorry not yet, i'm not on the ios app at the moment

**Comment by Saqib92** [comment]
one more thing can you please guide me to add `CustomUrlScheme` for IOS. somehow I am able to integrate this plugin and my app is now showing in the Share Sheet but I am not able to receive Data. Looks like something is misconfigured.

**Comment by carsten-klaffke** [comment]
[mcprol ](https://github.com/mcprol) has a solution for this in his fork https://github.com/mcprol/send-intent/tree/metricool. If you want to use it in my solution, you need to edit ShareViewController.swift as follows:

1) Replace the parent class "SLComposeServiceViewController" with "UIViewController"
2) Replace "didSelectPost" with "viewDidAppear"

That should do the trick.

**Comment by Saqib92** [comment]
> [mcprol ](https://github.com/mcprol) has a solution for this in his fork https://github.com/mcprol/send-intent/tree/metricool. If you want to use it in my solution, you need to edit ShareViewController.swift as follows:
> 
> 1. Replace the parent class "SLComposeServiceViewController" with "UIViewController"
> 2. Replace "didSelectPost" with "viewDidAppear"
> 
> That should do the trick.

i tried changing as you mentioned but it showing errors. 
also that fork have additional Steps which i didn't get. Can you explain all steps in details to use that @mcprol fork

**Comment by carsten-klaffke** [comment]
There were some more differences between the changed parent classes which I didn't see. Try this code for ShareViewController:

`//
//  ShareViewController.swift
//  mindlib
//
//  Created by Carsten Klaffke on 05.07.20.
//

import UIKit
import Social
import MobileCoreServices

class ShareItem {
    
       public var title: String?
       public var type: String?
       public var url: String?
}

class ShareViewController: UIViewController {

    private var shareItems: [ShareItem] = []
    

    override
       public func viewDidAppear(_ animated: Bool) {
           super.viewDidAppear(animated)

        let queryItems = shareItems.map { [URLQueryItem(name: "title", value: $0.title?.addingPercentEncoding(withAllowedCharacters: .urlHostAllowed) ?? ""), URLQueryItem(name: "description", value: ""), URLQueryItem(name: "type", value: $0.type?.addingPercentEncoding(withAllowedCharacters: .urlHostAllowed) ?? ""), URLQueryItem(name: "url", value: $0.url?.addingPercentEncoding(withAllowedCharacters: .urlHostAllowed) ?? "")] }.flatMap({ $0 })
        var urlComps = URLComponents(string: "YOUR_APP_URL_SCHEME://")!
        urlComps.queryItems = queryItems
        openURL(urlComps.url!)
        self.extensionContext!.completeRequest(returningItems: [], completionHandler: nil)
    }

    fileprivate func createSharedFileUrl(_ url: URL?) -> String {
        let fileManager = FileManager.default

        let copyFileUrl = fileManager.containerURL(forSecurityApplicationGroupIdentifier: "YOUR_APP_GROUP_ID")!.absoluteString.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)! + "/" + url!.lastPathComponent.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!
        try? Data(contentsOf: url!).write(to: URL(string: copyFileUrl)!)

        return copyFileUrl
    }

    override public func viewDidLoad() {
        super.viewDidLoad()
        
        shareItems.removeAll()
        
        let extensionItem = extensionContext?.inputItems[0] as! NSExtensionItem
        let contentTypeURL = kUTTypeURL as String
        let contentTypeText = kUTTypeText as String
        let contentTypeMovie = kUTTypeMovie as String
        let contentTypeImage = kUTTypeImage as String
       
        for attachment in extensionItem.attachments as! [NSItemProvider] {
            
            if attachment.hasItemConformingToTypeIdentifier(contentTypeURL) {
                attachment.loadItem(forTypeIdentifier: contentTypeURL, options: nil, completionHandler: { [self] (results, error) in
                    if results != nil {
                        let url = results as! URL?
                        let shareItem: ShareItem = ShareItem()
                        
                        if url!.isFileURL {
                            shareItem.title = url!.lastPathComponent
                            shareItem.type = "application/" + url!.pathExtension.lowercased()
                            shareItem.url = createSharedFileUrl(url)
                        } else {
                            shareItem.title = url!.absoluteString
                            shareItem.url = url!.absoluteString
                            shareItem.type = "text/plain"
                        }
                        
                        self.shareItems.append(shareItem)
                        
                    }
                })
            } else if attachment.hasItemConformingToTypeIdentifier(contentTypeText) {
                attachment.loadItem(forTypeIdentifier: contentTypeText, options: nil, completionHandler: { (results, error) in
                    if results != nil {
                        let shareItem: ShareItem = ShareItem()
                        let text = results as! String
                        shareItem.title = text
                        shareItem.type = "text/plain"
                        self.shareItems.append(shareItem)
                    }
                })
            } else if attachment.hasItemConformingToTypeIdentifier(contentTypeMovie) {
                attachment.loadItem(forTypeIdentifier: contentTypeMovie, options: nil, completionHandler: { [self] (results, error) in
                    if results != nil {
                        let shareItem: ShareItem = ShareItem()
                        
                        let url = results as! URL?
                        shareItem.title = url!.lastPathComponent
                        shareItem.type = "video/" + url!.pathExtension.lowercased()
                        shareItem.url = createSharedFileUrl(url)
                        self.shareItems.append(shareItem)
                    }
                })
            } else if attachment.hasItemConformingToTypeIdentifier(contentTypeImage) {
                attachment.loadItem(forTypeIdentifier: contentTypeImage, options: nil, completionHandler: { [self] (results, error) in
                    if results != nil {
                        let shareItem: ShareItem = ShareItem()
                        
                        let url = results as! URL?
                        shareItem.title = url!.lastPathComponent
                        shareItem.type = "image/" + url!.pathExtension.lowercased()
                        shareItem.url = createSharedFileUrl(url)
                        self.shareItems.append(shareItem)
                    }
                })
            }
        }
    }

    @objc func openURL(_ url: URL) -> Bool {
        var responder: UIResponder? = self
        while responder != nil {
            if let application = responder as? UIApplication {
                return application.perform(#selector(openURL(_:)), with: url) != nil
            }
            responder = responder?.next
        }
        return false
    }

}

`

Make sure to replace "YOUR_APP_URL_SCHEME" and "YOUR_APP_GROUP_ID".

**Comment by Saqib92** [comment]
> There were some more differences between the changed parent classes which I didn't see. Try this code for ShareViewController:
> 
> ```
> //
> //  ShareViewController.swift
> //  mindlib
> //
> //  Created by Carsten Klaffke on 05.07.20.
> //
> 
> import UIKit
> import Social
> import MobileCoreServices
> 
> class ShareItem {
>     
>        public var title: String?
>        public var type: String?
>        public var url: String?
> }
> 
> class ShareViewController: UIViewController {
> 
>     private var shareItems: [ShareItem] = []
>     
> 
>     override
>        public func viewDidAppear(_ animated: Bool) {
>            super.viewDidAppear(animated)
> 
>         let queryItems = shareItems.map { [URLQueryItem(name: "title", value: $0.title?.addingPercentEncoding(withAllowedCharacters: .urlHostAllowed) ?? ""), URLQueryItem(name: "description", value: ""), URLQueryItem(name: "type", value: $0.type?.addingPercentEncoding(withAllowedCharacters: .urlHostAllowed) ?? ""), URLQueryItem(name: "url", value: $0.url?.addingPercentEncoding(withAllowedCharacters: .urlHostAllowed) ?? "")] }.flatMap({ $0 })
>         var urlComps = URLComponents(string: "YOUR_APP_URL_SCHEME://")!
>         urlComps.queryItems = queryItems
>         openURL(urlComps.url!)
>         self.extensionContext!.completeRequest(returningItems: [], completionHandler: nil)
>     }
> 
>     fileprivate func createSharedFileUrl(_ url: URL?) -> String {
>         let fileManager = FileManager.default
> 
>         let copyFileUrl = fileManager.containerURL(forSecurityApplicationGroupIdentifier: "YOUR_APP_GROUP_ID")!.absoluteString.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)! + "/" + url!.lastPathComponent.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!
>         try? Data(contentsOf: url!).write(to: URL(string: copyFileUrl)!)
> 
>         return copyFileUrl
>     }
> 
>     override public func viewDidLoad() {
>         super.viewDidLoad()
>         
>         shareItems.removeAll()
>         
>         let extensionItem = extensionContext?.inputItems[0] as! NSExtensionItem
>         let contentTypeURL = kUTTypeURL as String
>         let contentTypeText = kUTTypeText as String
>         let contentTypeMovie = kUTTypeMovie as String
>         let contentTypeImage = kUTTypeImage as String
>        
>         for attachment in extensionItem.attachments as! [NSItemProvider] {
>             
>             if attachment.hasItemConformingToTypeIdentifier(contentTypeURL) {
>                 attachment.loadItem(forTypeIdentifier: contentTypeURL, options: nil, completionHandler: { [self] (results, error) in
>                     if results != nil {
>                         let url = results as! URL?
>                         let shareItem: ShareItem = ShareItem()
>                         
>                         if url!.isFileURL {
>                             shareItem.title = url!.lastPathComponent
>                             shareItem.type = "application/" + url!.pathExtension.lowercased()
>                             shareItem.url = createSharedFileUrl(url)
>                         } else {
>                             shareItem.title = url!.absoluteString
>                             shareItem.url = url!.absoluteString
>                             shareItem.type = "text/plain"
>                         }
>                         
>                         self.shareItems.append(shareItem)
>                         
>                     }
>                 })
>             } else if attachment.hasItemConformingToTypeIdentifier(contentTypeText) {
>                 attachment.loadItem(forTypeIdentifier: contentTypeText, options: nil, completionHandler: { (results, error) in
>                     if results != nil {
>                         let shareItem: ShareItem = ShareItem()
>                         let text = results as! String
>                         shareItem.title = text
>                         shareItem.type = "text/plain"
>                         self.shareItems.append(shareItem)
>                     }
>                 })
>             } else if attachment.hasItemConformingToTypeIdentifier(contentTypeMovie) {
>                 attachment.loadItem(forTypeIdentifier: contentTypeMovie, options: nil, completionHandler: { [self] (results, error) in
>                     if results != nil {
>                         let shareItem: ShareItem = ShareItem()
>                         
>                         let url = results as! URL?
>                         shareItem.title = url!.lastPathComponent
>                         shareItem.type = "video/" + url!.pathExtension.lowercased()
>                         shareItem.url = createSharedFileUrl(url)
>                         self.shareItems.append(shareItem)
>                     }
>                 })
>             } else if attachment.hasItemConformingToTypeIdentifier(contentTypeImage) {
>                 attachment.loadItem(forTypeIdentifier: contentTypeImage, options: nil, completionHandler: { [self] (results, error) in
>                     if results != nil {
>                         let shareItem: ShareItem = ShareItem()
>                         
>                         let url = results as! URL?
>                         shareItem.title = url!.lastPathComponent
>                         shareItem.type = "image/" + url!.pathExtension.lowercased()
>                         shareItem.url = createSharedFileUrl(url)
>                         self.shareItems.append(shareItem)
>                     }
>                 })
>             }
>         }
>     }
> 
>     @objc func openURL(_ url: URL) -> Bool {
>         var responder: UIResponder? = self
>         while responder != nil {
>             if let application = responder as? UIApplication {
>                 return application.perform(#selector(openURL(_:)), with: url) != nil
>             }
>             responder = responder?.next
>         }
>         return false
>     }
> 
> }
> ```
> 
> Make sure to replace "YOUR_APP_URL_SCHEME" and "YOUR_APP_GROUP_ID"!

Thank you so much. it worked. But now the returned data is changed.

**Comment by j-d-carmichael** [comment]
I just built a new project with the lastest and it works perfectly
