### ISSUE TITLE
"No processing needed" error messages in android

### ISSUE THREAD

**Issue by Paso** [carsten-klaffke/send-intent#17]
The app works as expected after setup according to the instructions but the lib is sending lots of unnecessary error messages "No processing needed".

The intents that are not beeing handled by the lib are of the following type:

Intent { act=intent handled cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=app.name/.MainActivity }

**Comment by carsten-klaffke** [comment]
Hello Paso,
this is the response message you will receive after actively checking for intents, if no intent of type SEND is found (or if the content is not processable for the plugin). I think I have to send a response to cleanly resolve the call. 
You could check whether you can adjust the way you use it (do not call it to often, try to call once on application startup) or rely on the handling as listener (don't actively call at all).

**Comment by Paso** [comment]
Ah, that makes sense. 

I was using the listener method but was also calling checkSendIntentReceived as I expected the listener to not catch intents before being registered, but also had a bug where it was called more often then that. 

Sorry for bothering you.
