### ISSUE TITLE
Not Receiving Data in IOS

### ISSUE THREAD

**Issue by Saqib92** [carsten-klaffke/send-intent#19]
Thanks for This Great Plugin for Capacitor. I am able to receive data from Instagram `Share To` option in android but in IOS its not working. 
I tried with both via `addListener()` and normally but nothing is working in IOS. My Application shows in Share Sheet but not receiving data.

**Comment by carsten-klaffke** [comment]
Please double check the instructions in readme! Do you get some data in the ShareViewController? If not, please show me your Code for the ShareViewController and the relevant part of AppDelegate! And also let me know how you try to share from instagram, as some data sources are problematic. You can also check yourself by trying it with my app "mindlib - your personal mind library". This will show you whether it is a configuration problem or a general problem with the plugin.

**Comment by Saqib92** [comment]
ShareViewController.swift

```
import UIKit
import Social
import MobileCoreServices

class ShareViewController: SLComposeServiceViewController {

    private var urlString: String?
    private var textString: String?
    private var imageString: String?
    private var fileString: String?

    override func isContentValid() -> Bool {
        // Do validation of contentText and/or NSExtensionContext attachments here
        print(contentText ?? "content is empty")
        return true
    }

    override func didSelectPost() {
        var urlString = "https://fvweb.yaze.live/" + (self.textString ?? "");
        urlString = urlString + "&url=" + (self.urlString ?? "");
        urlString = urlString + "&image=" + (self.imageString ?? "");
        urlString = urlString + "&file=" + (self.fileString?.addingPercentEncoding(withAllowedCharacters: .urlHostAllowed) ?? "");
        let url = URL(string: urlString)!
        openURL(url)
        self.extensionContext!.completeRequest(returningItems: [], completionHandler: nil)
    }

    override func configurationItems() -> [Any]! {
        // To add configuration options via table cells at the bottom of the sheet, return an array of SLComposeSheetConfigurationItem here.
        return []
    }

    override func viewDidLoad() {
      super.viewDidLoad()

      let extensionItem = extensionContext?.inputItems[0] as! NSExtensionItem
      let contentTypeURL = kUTTypeURL as String
      let contentTypeText = kUTTypeText as String

      for attachment in extensionItem.attachments as! [NSItemProvider] {

          attachment.loadItem(forTypeIdentifier: contentTypeURL, options: nil, completionHandler: { (results, error) in
                if results != nil {
                let url = results as! URL?
                if url!.isFileURL {
                    do {
                        self.fileString = try! String(contentsOf: url!, encoding: .utf8)
                    }
                } else {
                    self.urlString = url!.absoluteString
                }
            }
          })

          attachment.loadItem(forTypeIdentifier: contentTypeText, options: nil, completionHandler: { (results, error) in
            if results != nil {
                let text = results as! String
                self.textString = text
                _ = self.isContentValid()
            }
          })

      }
    }

    @objc func openURL(_ url: URL) -> Bool {
        var responder: UIResponder? = self
        while responder != nil {
            if let application = responder as? UIApplication {
                return application.perform(#selector(openURL(_:)), with: url) != nil
            }
            responder = responder?.next
        }
        return false
    }

}
```

AppDelegate.swift

```
...
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {
        // Called when the app was launched with a url. Feel free to add additional processing here,
        // but if you want the App API to support tracking app url opens, make sure to keep this call
        //return ApplicationDelegateProxy.shared.application(app, open: url, options: options)
        if (FBSDKCoreKit.ApplicationDelegate.shared.application(
            app,
            open: url,
            sourceApplication: options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String,
            annotation: options[UIApplication.OpenURLOptionsKey.annotation]
        )) {
            var success = true

            if CAPBridge.handleOpenUrl(url, options) {
                    success = FBSDKCoreKit.ApplicationDelegate.shared.application(app, open: url, options: options)
                    }

                    guard let components = NSURLComponents(url: url, resolvingAgainstBaseURL: true),
                        let params = components.queryItems else {
                            return false
                    }
                    store.text = params.first(where: { $0.name == "text" })?.value as! String
                    store.url = params.first(where: { $0.name == "url" })?.value as! String
                    store.image = params.first(where: { $0.name == "image" })?.value as! String
                    store.file = params.first(where: { $0.name == "file" })?.value?.removingPercentEncoding as! String
                    store.processed = false
                    let nc = NotificationCenter.default
                    nc.post(name: Notification.Name("triggerSendIntent"), object: nil )
            return success;
        } else {
            return ApplicationDelegateProxy.shared.application(app, open: url, options: options)
        }
    }
...
```

XCode Logs on Sharing:

> ⚡️  TO JS {"iosSourceApplication":"","url":"https:\/\/fvweb.yaze.live\/&url=https:\/\/www.instagram.com\/p\/CTCbbILps9z\/?utm_medium=share_sheet&image=&file=","iosOpenInPlace":""}
> ⚡️  [error] - ERROR {}
> ⚡️  [error] - ERROR {}
> ⚡️  [error] - ERROR {"rejection":{},"promise":{"__zone_symbol__state":0,"__zone_symbol__value":"..."},"zone":{"_parent":{"_parent":null,"_name":"<root>","_properties":{},"_zoneDelegate":{"_taskCounts":{"microTask":0,"macroTask":0,"eventTask":0},"zone":"...","_parentDelegate":null,"_forkZS":null,"_forkDlgt":null,"_forkCurrZone":null,"_interceptZS":null,"_interceptDlgt":null,"_interceptCurrZone":null,"_invokeZS":null,"_invokeDlgt":null,"_invokeCurrZone":null,"_handleErrorZS":null,"_handleErrorDlgt":null,"_handleErrorCurrZone":null,"_scheduleTaskZS":null,"_scheduleTaskDlgt":null,"_scheduleTaskCurrZone":null,"_invokeTaskZS":null,"_invokeTaskDlgt":null,"_invokeTaskCurrZone":null,"_cancelTaskZS":null,"_cancelTaskDlgt":null,"_cancelTaskCurrZone":null,"_hasTaskZS":null,"_hasTaskDlgt":null,"_hasTaskDlgtOwner":null,"_hasTaskCurrZone":null}},"_name":"angular","_properties":{"isAngularZone":true},"_zoneDelegate":{"_taskCounts":{"microTask":0,"macroTask":0,"eventTask":150},"zone":"...","_parentDelegate":"...","_forkZS":null,"_forkDlgt":null,"_forkCurrZone":null,"_interceptZS":null,"_interceptDlgt":null,"_interceptCurrZone":null,"_invokeZS":{"name":"angular","properties":"..."},"_invokeDlgt":"...","_invokeCurrZone":"...","_handleErrorZS":"...","_handleErrorDlgt":"...","_handleErrorCurrZone":"...","_scheduleTaskZS":{"name":""},"_scheduleTaskDlgt":"...","_scheduleTaskCurrZone":"...","_invokeTaskZS":"...","_invokeTaskDlgt":"...","_invokeTaskCurrZone":"...","_cancelTaskZS":"...","_cancelTaskDlgt":"...","_cancelTaskCurrZone":"...","_hasTaskZS":"...","_hasTaskDlgt":"...","_hasTaskDlgtOwner":"...","_hasTaskCurrZone":"..."}},"task":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","runCount":0}}
> 2021-09-13 15:05:03.759124+0500 App[8675:1974594] [connection] nw_endpoint_handler_set_adaptive_read_handler [C7.1 142.250.181.74:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for read_timeout failed
> 2021-09-13 15:05:03.760067+0500 App[8675:1974594] [connection] nw_endpoint_handler_set_adaptive_write_handler [C7.1 142.250.181.74:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed

**Comment by carsten-klaffke** [comment]
The first call 
 TO JS {"iosSourceApplication":"","url":"https://fvweb.yaze.live/&url=https://www.instagram.com/p/CTCbbILps9z/?utm_medium=share_sheet&image=&file=","iosOpenInPlace":""}
 implies that the iOS side of the plugin works, as you received the instagram url correctly. 
 I am not sure about your URL prefix "https://fvweb.yaze.live/". I think you have to address an internal name. In my case it looks as following:
 `override func didSelectPost() {
        var urlString = "mindlib://?text=" + (self.textString ?? "");
        urlString = urlString + "&url=" + (self.urlString ?? "");
        urlString = urlString + "&image=" + (self.imageString ?? "");
        urlString = urlString + "&file=" + (self.fileString?.addingPercentEncoding(withAllowedCharacters: .urlHostAllowed) ?? "");
        let url = URL(string: urlString)!
        openURL(url)
        self.extensionContext!.completeRequest(returningItems: [], completionHandler: nil)
    }`
    And afterwards you have an error in your promise on client side. Maybe this error is a follow up of the prefix, but it could be the original error you are looking for, as well.

**Comment by Saqib92** [comment]
I changed my URL prefix: `fvwebyazelive://?text=`
my Application get open but still having same Error.

**Comment by carsten-klaffke** [comment]
Die you register a URL scheme for "fvwebyazelive" like described in https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app ?

**Comment by Saqib92** [comment]
Yes, I did. but i still doubt i misconfigured it  :(

**Comment by Saqib92** [comment]
Logs From Safari DevTool:
![Screenshot 2021-09-13 at 5 16 35 PM](https://user-images.githubusercontent.com/7135885/133081913-66e4bd15-8b2a-46d8-a6f9-1ad9c289e59f.png)

**Comment by carsten-klaffke** [comment]
Yes, the configuration looks good to me, too. 
Please check if you get into the function "func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:])" in AppDelegate.swift. The mechanism is:
1. Collect data in share extension
2. Post data to iOS app (this is what you need the URL scheme for)
3. Write data to a store and trigger the intent listener
To me, it looks like the POST from the share extension doesn't reach the app.

**Comment by Saqib92** [comment]
Solved it 🥇 .

It wasn't a Misconfiguration neither Plugin Issue. 
Real Culprit was Deeplinks setup in my app: 
https://capacitorjs.com/docs/apis/app
https://capacitorjs.com/docs/guides/deep-links#angular

i am using `APP` api from Capacitor for Deeplinks in my application to open my app from links.

I have this code in my App:

```
setupDeepLink() {
    App.addListener('appUrlOpen', (event: URLOpenListenerEvent) => {
      this.zone.run(() => {
        const slug = event.url.split("/tabs").pop();
        if (slug) {
          this.general.goToPage('/tabs' + slug);
        }
      });
    });
}
```

And when ever I tried to Share Anything to my app using your Send-Intent Plugin my `App.addListener` from above function gets called and tries to redirect as per the logic written in it. Now i think we should do some Testing of your plugin and APP api from capacitor with deeplink setup to check why this is happening.

**Comment by carsten-klaffke** [comment]
Ah, I see. That explains it. I would say the deepLink listeners' code must ignore the sendIntent requests. You could use your URLScheme to distinguish here.

**Comment by Saqib92** [comment]
I am Brain Dead right now. It took my Whole day just to figure out this bug. What should i Do 😆  how should i distinguished it

**Comment by carsten-klaffke** [comment]
I was thinking of something like:
`setupDeepLink() {
    App.addListener('appUrlOpen', (event: URLOpenListenerEvent) => {
      if(event.url.startsWith('fvwebyazelive:'))
          return
      this.zone.run(() => {
        const slug = event.url.split("/tabs").pop();
        if (slug) {
          this.general.goToPage('/tabs' + slug);
        }
      });
    });
}`

**Comment by Saqib92** [comment]
Somehow I managed to make it work for now. But is there any way to ignore Deeplink listeners when coming from your plugin. is it on your End or should report it to capacitor repo with reference to your plugin. Also can you add this plugin to official Community it will be very help full. Thanks Again. 👍🏽

**Comment by carsten-klaffke** [comment]
Great! As DeepLink registers a listener to the appUrlOpen-event, I wouldn't know a good way of preventing this. To me, the communication the send-intent plugin does should be ignored in DeepLink, as I described above. Thank you for the hint to the Capacitor Community. I already attached the plugin to an existing issue (https://github.com/capacitor-community/proposals/issues/46) a while ago.
