### ISSUE TITLE
error when using the plugin : no processing needed.

### ISSUE THREAD

**Issue by sbsystemscoders** [carsten-klaffke/send-intent#31]
Hi, I found your plugin and I'm hoping its what I need for my use-case. I want to use this as a listener for text data that is being set in an intent from a specific app (in Android). I have followed the set up but I'm getting the error "no processing needed".
What should I look for to resolve this issue? I have added the intent filters as in the example, and the code in the main-activity as well as the listener code in my app.tsx. I have also removed all existing listeners for deeplinks in my app as well as rebuilt the project.
Hoping you can help.

**Comment by carsten-klaffke** [comment]
The message "No processing needed" can be ignored in most cases. E.g. if you have configured the plugin to request intents on app startup, then there is not always a send intent to process.
In your case, did you share something to your app and then only received "No processing needed"? Did you configure send intent both triggered on app startup and as a listener (as described in readme)?

**Comment by sbsystemscoders** [comment]
Ok that makes sense. the error message only shows on initial app start up. I've shared some text data but this is not being picked up by logging or alerts on my app (at this point no further 'no processing needed' messages are showing). I'm still relatively new to capacitor so please forgive me if I've missed something.  The data that would be processed is from a third party app is being added via the intent code below.

`
//intent code from the third part app. 
try  {
        Intent intent = getPackageManager().getLaunchIntentForPackage("com.hebs.myapp");
        if (intent != null) {
	        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
	        intent.putExtra("COMPANY_UUID","test 1");
	        intent.putExtra("JOB_NO","JN1234");
	        intent.setType("text/plain");
        
	        startActivity(intent);
	        
        } else {
	        // Bring user to the market or let them choose an app?
	        intent = new Intent(Intent.ACTION_VIEW);
	        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
	        intent.setData(Uri.parse("market://details?id=" + "com.hebs.myapp"));
	        startActivity(intent);
        }
	} catch (Exception ex) {
	}
`

The code provided by your readme I've put inside a component that is inside my react router, so that it will fire on each app start up:


`
//Listener component
const AppUrlListener: React.FC<any> = () => {

      SendIntent.checkSendIntentReceived().then((result: any) => {
        console.log(result)
        alert("intent recieved")
        if (result) {
          alert('SendIntent received: ' + JSON.stringify(result))
            console.log('SendIntent received');  
            console.log(JSON.stringify(result));
        }
        if (result.url) {
            let resultUrl = decodeURIComponent(result.url);
            console.log(resultUrl)
            //Filesystem.readFile({path: resultUrl})
            //.then((content) => {
                //console.log(content.data);
            //})
            //.catch((err) => console.error(err));
        }
    }).catch(err => console.error(err));
    return null;
  };
  
    return null;
  };

`

The listener code I have also added to my app.tsx file:


`
  document.addEventListener("sendIntentReceived", () => {
    SendIntent.checkSendIntentReceived().then((result: any) => {
         if (result) {
             // ...
             console.log(result);
             alert(result)
         }
     });
  })
`


I understand "no processing needed" will fire if the app starts without being prompted by an intent. But on testing this with an emulator, I open the third party app and press the button to create the intent and move over to my capacitor app. My app is fired up but no intent data is alerted of logged. Is my setup wrong? Will this not fire if my capacitor app is backgrounded when being called by another app or should it fire on every open event?
I cant see what I will need to check for in order to test for data. Thanks for your advice. I believe I've missed something crucial in my setup. I'm happy to provide more info if required.

**Comment by carsten-klaffke** [comment]
It looks like you are missing one part of the listener mechanism. You need to overwrite "onNewIntent" in your MainActivity. And make sure that the type of the intent you receive is "ACTION_SEND". If it is not, you might have to adjust it, because the plugin only listens to this type.

`@Override
protected void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
    String action = intent.getAction();
    String type = intent.getType();
    if (Intent.ACTION_SEND.equals(action) && type != null) {
        bridge.getActivity().setIntent(intent);
        bridge.eval("window.dispatchEvent(new Event('sendIntentReceived'))", new ValueCallback<String>() {
            @Override
            public void onReceiveValue(String s) {
            }
        });
    }
}`

**Comment by sbsystemscoders** [comment]
Thanks. Sorry I forgot to add that I have added that code in my main activity. I did check this and it is listening to Action.Send.

my main Activity@
`
import android.content.Intent;
import android.webkit.ValueCallback;
import android.os.Bundle;

import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {

    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        String action = intent.getAction();
        String type = intent.getType();
        if (Intent.ACTION_SEND.equals(action) && type != null) {
            bridge.getActivity().setIntent(intent);
            bridge.eval("window.dispatchEvent(new Event('sendIntentReceived'))", new ValueCallback<String>() {
                @Override
                public void onReceiveValue(String s) {
                }
            });
        }
    }

}

`


My Intent Filter:
`
<activity
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
            android:name="com.hebs.myapp.MainActivity"
            android:label="@string/title_activity_main"
            android:theme="@style/AppTheme.NoActionBarLaunch"
            android:launchMode="singleTask">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/custom_url_scheme" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="image/*" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.SEND"  />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="text/plain" />
            </intent-filter>


        </activity>
`

Thanks again for looking.

**Comment by carsten-klaffke** [comment]
Can you debug "onNewIntent" and confirm that the method is reached by your other apps intent? If not, there is probably a filter wrong, but I can't see a mistake on first look. If yes, then maybe the type of the intent is not "ACTION_SEND"?
From your code (below), I don't see where the type "ACTION_SEND" is set.

```
try {
Intent intent = getPackageManager().getLaunchIntentForPackage("com.hebs.myapp");
if (intent != null) {
intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
intent.putExtra("COMPANY_UUID","test 1");
intent.putExtra("JOB_NO","JN1234");
intent.setType("text/plain");
startActivity(intent);
...
```

**Comment by sbsystemscoders** [comment]
Sorry for the late update, been away for the weekend
Debugging hits "onNewIntent" just fine. I added a line to set the action as Action_Send on the intent of the third party app, and edited the intent filter to receive "text/*" just in case.
Stepping through the "onNewIntent " method, I noticed that it does not drop into code "public void onReceiveValue(String s)" from the bridge.eval method but skips it ( I guess this is because its running some js callback ).
So I'm a bit stuck on where to proceed. 
I understand this could be many things in relation to my app code and setup, but if you have any more thoughts I'd appreciate it.

**Comment by sbsystemscoders** [comment]
Also to add to the above. It seems that the listener works if I'm just opening the app in a browser as the image suggests..

![image](https://user-images.githubusercontent.com/66617972/144838264-a1d87166-1a7a-4200-907f-0e1e9b201ac2.png)

**Comment by carsten-klaffke** [comment]
I think we are close. The event should be fired now. But I guess you have a problem on the receiving side. I noticed you attached the eventListener to "document". Try attaching it to "window" (window.addEventListener...). It is correct that onReceiveValue dosen't do anything. This is just for callback which we don't need here.

**Comment by sbsystemscoders** [comment]
Using window causes my app to crash when loading via a third party intent (android message  myapp keeps stopping). Not sure why this is happening, so I changed to document.

**Comment by carsten-klaffke** [comment]
Then you have to adjust it to "document" in the MainActivity as well (in onNewIntent() bridge.eval(document. ...). Not sure if it works on document, otherwise you have to get "window" running on your app.

**Comment by sbsystemscoders** [comment]
Thanks. Changing MainActivity to document didn't work. Ill look into fixing window in my app. Thanks

**Comment by sbsystemscoders** [comment]
Maybe making some headway. I'm using capacitor 3. The listener of my capacitor app fires on app open via intent from the third party app, I now get this stack trace in the android console when it tries to open:

> 

2021-12-07 12:50:31.146 31321-31391/com.hebs.myapp E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:592)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ClipData$Item android.content.ClipData.getItemAt(int)' on a null object reference
        at de.mindlib.sendIntent.SendIntent.readItemAt(SendIntent.java:47)
        at de.mindlib.sendIntent.SendIntent.checkSendIntentReceived(SendIntent.java:29)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:592) 
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2021-12-07 12:50:31.147 31321-31391/com.hebs.myapp E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: com.hebs.myapp, PID: 31321
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:601)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:592)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ClipData$Item android.content.ClipData.getItemAt(int)' on a null object reference
        at de.mindlib.sendIntent.SendIntent.readItemAt(SendIntent.java:47)
        at de.mindlib.sendIntent.SendIntent.checkSendIntentReceived(SendIntent.java:29)


Can you pull anything form tis that may help? do I need to register the plugin?

**Comment by carsten-klaffke** [comment]
The problem here is that your partner app doesn't create an intent like Android OS would. The intent's content is filled in a different way. I see two solutions: 
1) Mimic the behaviour of Android OS by filling your intent in "onNewIntent". For this you would have to do something like intent.putExtra(Intent.EXTRA_SUBJECT, intent.getStringExtra("COMPANY_UUID"));
intent.putExtra(Intent.EXTRA_TEXT,  intent.getStringExtra("JOB_NO"));
intent.setClipData(new ClipData(null, null, null));
You should then get your data in "title" (->"COMPANY_UUID")  and "url" (-> "JOB_NO").
2) Create a fork and do a custom mapping

**Comment by sbsystemscoders** [comment]
I managed to get messages into my app! I ended up leaving the third party intent and instead modifying the plugin at SendIntent.readItemAt() to read intent.getExtras() as a bundle. I need to tidy up a little but it seems to pass data to my app now. I've added the modded code for others that may want to do similar.

`
private JSObject readItemAt(Intent intent, String type, int index) {
        JSObject ret = new JSObject();
        String title = intent.getStringExtra(Intent.EXTRA_TEXT);
        Bundle x = intent.getExtras();
        ret.put("title", title);
        ret.put("description", null);
        ret.put("type", type);
        ret.put("CompanyUUID", (x!=null) ? x.get("COMPANY_UUID").toString() : null);
        ret.put("JobNo", (x!=null) ? x.get("JOB_NO").toString() : null);
        return ret;
    }
` 

Thank you so much for taking the time to help with this. Its really appreciated. I'm fresh out of bitcoin but if you have another way to send some thanks (buy a coffee ect), pop it it on your npm page :)

**Comment by carsten-klaffke** [comment]
I'm glad to hear that. You're welcome and I love coffee, so that would be much appreciated! I added a stripe option for this purpose. You can find it at the bottom of readme.

**Comment by sbsystemscoders** [comment]
Done. Enjoy
