### ISSUE TITLE
Capacitor WebPlugin "SendIntent" config object was deprecated in v3 and will be removed in v4.

### ISSUE THREAD

**Issue by MichaelMaenner** [carsten-klaffke/send-intent#40]
I noticed this warning today in the web console of our angular application. 

`Capacitor WebPlugin "SendIntent" config object was deprecated in v3 and will be removed in v4.`

We are using `angular 11`, `capacitor ^3.4.0` and `send-intent 3.0.10` 

---

It's just a warning and doesn't currently affect our application - but I just wanted to let you know about it :)

**Comment by carsten-klaffke** [comment]
Thank you for the hint! I just fixed this with send-intent:3.0.11.
