### ISSUE TITLE
There's no send intent of video data

### ISSUE THREAD

**Issue by adrianorod** [carsten-klaffke/send-intent#5]
I was trying to send an intent of video, but has an error occurring:

`E/Capacitor/Console: File: capacitor-runtime.js - Line 229 - Msg: Uncaught (in promise) Error: No processing needed`

I imagine that has no implementation for this type of data. It would be nice an improvement like that.

**Comment by carsten-klaffke** [comment]
Hi Adriano!
Exactly, this type is not yet handled. To do that, you would need to add it in the method "SendIntent:checkSendIntentReceived()" for Android.  iOS would be more complicated as you have to adjust "Plugin.swift", "ShareStore.swift" and the Code I mentioned in the README.
I need an extension for handling files in the near future myself, so I will work on the plugin and maybe add video too. But I can't promise as it might be some effort (encoding could be a problem) and I don't need it myself. If you want to give it a try, you can ask me questions for support and I would include it as a pull request.
Best regards
Carsten

**Comment by mcprol** [comment]
I have added support for video files in my fork, https://github.com/mcprol/send-intent/tree/metricool, if it helps

**Comment by carsten-klaffke** [comment]
Thank you Marcos! I also integrated video support now in the root project. Check the updated Readme.md for the ShareViewController.swift and AppDelegate.swift. You would also have to adjust the share extension's activation rules (also updated in my Readme.md). On the receiving side, you will get an URL which you can read out with the Capacitor "Filesystem" plugin.
