### ISSUE TITLE
Unable to get extra data while i hit only data i get is type text/plain

### ISSUE THREAD

**Issue by vinit-poojary** [carsten-klaffke/send-intent#54]
I was trying to get multiple data from another app 
The only thing I am receiving is `{"type": "text/plain"}`

also, the plugin does not work if the app is open am I missing something I have to close the app to get data

**Comment by carsten-klaffke** [comment]
Hello @vinit-poojary, is this problem on Android or iOS? What exactly are you trying to share? Multiple text-files at once?
