### ISSUE TITLE
Error: SendIntent plugin is not implemented on android

### ISSUE THREAD

**Issue by seth100** [carsten-klaffke/send-intent#58]
Hi,

I'm using this plugin on my Capacitor v4 + Nuxt v2.15.8 app and I'm getting the following error:

```
Error: "SendIntent" plugin is not implemented on android
```

using the following code in my `index.vue` page:

```js
import { SendIntent } from 'send-intent';

mounted() {
    if (this.$device.isNative) {
      SendIntent.checkSendIntentReceived()
        .then((result) => {
          // ...

          SendIntent.finish();
        })
        .catch(err => alert(err));
    }
},
```

what am I doing wrong? Is that an issue with new Capacitor versions or I need to register the plugin somehow?

Thanks

**Comment by carsten-klaffke** [comment]
Hi! Which version of send-intent are you using? With Capacitor 4 it should be > 3.

**Comment by seth100** [comment]
> Hi! Which version of send-intent are you using? With Capacitor 4 it should be > 3.

yes, latest `3.0.11`

**Comment by seth100** [comment]
thank you, I'll try that!
