### ISSUE TITLE
Dependencies "-"

### ISSUE THREAD

**Issue by MichaelMaenner** [carsten-klaffke/send-intent#59]
Hey Carsten, 

i just stumbled across a dependency inside my package-lock.json file.

```
"dependencies": {
    "-": {
      "version": "0.0.1",
      "resolved": "https://registry.npmjs.org/-/-/--0.0.1.tgz",
      "integrity": "sha512-3Hfne...
```

In the dependencies tab from npmjs `-` is listed as one of your dependencies. 
https://www.npmjs.com/package/send-intent

I just wanted to let you know ;)

**Comment by carsten-klaffke** [comment]
Hey Michael,

thanks a lot for reporting this!

What exactly does that mean? Is this just something unused that came into the repository by accident or is it even malicious? I can see that it originates from a commit of a contributor and it is already some time ago. Hopefully, that caused no damage!

Best regards
Carsten

Von: MichaelMaenner ***@***.***>
Datum: Mittwoch, 31. August 2022 um 18:08
An: carsten-klaffke/send-intent ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [carsten-klaffke/send-intent] Dependencies "-" (Issue #59)

Hey Carsten,

i just stumbled across a dependency inside my package-lock.json file.

"dependencies": {

    "-": {

      "version": "0.0.1",

      "resolved": "https://registry.npmjs.org/-/-/--0.0.1.tgz",

      "integrity": "sha512-3Hfne...

In the dependencies tab from npmjs - is listed as one of your dependencies.
https://www.npmjs.com/package/send-intent

I just wanted to let you know ;)

**Comment by carsten-klaffke** [comment]
I removed this dependency.
