### ISSUE TITLE
Can't add informations to my intent using putExtra

### ISSUE THREAD

**Issue by Lineaum** [carsten-klaffke/send-intent#60]
Hello, first of all thanks for this package, I was close to giving up when I found it. i'm using Ionic 6.2, Capacitor 4.

I added two activities, each having it's intent-filter in my app on Android side for now. 
Indeed, I would like to have 2 buttons in the Android ShareSheet triggering two different scenarios for the files I share.

![image](https://user-images.githubusercontent.com/28531126/194892234-3e68c56f-1418-4a0b-8e9d-cb4cedf1fc27.png)

I thought about using putExtra for each intent and set a 'verb' so that when my app lauches I can check the value of this 'verb' and determine what to do accordingly (scenario 1 or 2).

![image](https://user-images.githubusercontent.com/28531126/194888252-2310ccb6-e803-4c10-80e8-2d52c8bc1c87.png)

However even with the intent having a putExtra to it the structure of the intent when calling checkSendIntentReceived() stays the following (thanks to an JSON.stringify of the result) :

![image](https://user-images.githubusercontent.com/28531126/194888656-60e592fa-d3a3-4ae8-ad3c-c5823a2a15cf.png)
 
And that's it, I thought I could retrieve the 'verb' into the additionalItems of the Intent's interface but it ain't there.
Or maybe could I use the description field and how ?

For now I'm going to have only one button in the ShareSheet, so only one activity and intent.
I will add a page in my app asking the user which scenario he wants to be done with the file but for a future update it would be awesome to be able to have both ! :)

**Comment by carsten-klaffke** [comment]
Hello! 

I think the "extra"-attribute isn't read by the plugin. Unfortunately, "description" works only for iOS. You could use either one of "type", "title" or "url", where each has some logic how it is read by the plugin. So look at _SendIntent.java_ to understand how the values will be evaluated! You could also branch/PR if you want to add and use "description" instead.
I am not 100% sure if it will display two buttons on the ShareSheet, but I'd try to define two activities in the _AndroidManifest.xml_. 
Then, to distinguish between these two activities in the plugin, I would derive two classes from _SendIntentActivity.java_ and link them in the corresponding _AndroidManifest.xml_-activity. Like that:

```
<activity
            android:name=".yourpackage.Activity1"
...
```

An activity itself should then look like this:

```
package yourpackage;

import android.content.Intent;

import de.mindlib.sendIntent.SendIntentActivity;

public class Activity1 extends SendIntentActivity {

    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        intent.setType("add");
    }

}

```

As I said, using "type" would be just an option. It would override file types and you might need them.

I hope this helps you and works out.

Best regards
Carsten

**Comment by Lineaum** [comment]
Hi, thanks for the quick answer,

I'm sorry I was unclear the two buttons already works fine with defining two activities yes ! ;)
However, the activities's classes are quite empty for now and it's working (I might be lucky though). Indeed, I've put everything from "public void OnCreate" into comment and everything is still working.

I will have a look into SendIntentAcitivity.java and refactor my activities to make sure it keeps on working in the future, thanks again !

**Comment by Lineaum** [comment]
Yep everything is working fine for Android, I'm closing it now, thanks again for the help and the reminder
