### ISSUE TITLE
class file for androidx.appcompat.app.AppCompatActivity not found

### ISSUE THREAD

**Issue by avantgarde0707** [carsten-klaffke/send-intent#7]
Hi,

i'm using capacitor 3.0 and having same issue discribed/solved here:
https://github.com/capacitor-community/firebase-analytics/issues/55#issuecomment-810376556

maybe also necessary to backport here?

**Comment by d00ML0rDz** [comment]
I'm seeing a similar thing too.

![image](https://user-images.githubusercontent.com/66832778/124389073-7a241400-dcdd-11eb-9acc-dcce962aa6e4.png)

**Comment by carsten-klaffke** [comment]
Hey, thank you for informing me about this issue. I just added the missing dependency. I uploaded it with send-intent:1.1.7. Please give me feedback if this solves your problem!

**Comment by avantgarde0707** [comment]
Works like a charm... tnx!
closing issue
