### ISSUE TITLE
Changelog? What changed in v3?

### ISSUE THREAD

**Issue by marcelklehr** [carsten-klaffke/send-intent#74]
**Is your feature request related to a problem? Please describe.**
I've been using v2 so far. Now I noticed v3 is out. What changed? There's no info available.

**Describe the solution you'd like**
Provide a changelog.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by carsten-klaffke** [comment]
The major version change was for Capacitor3 support. Please check the regular git log for a detailed change overview!

**Comment by marcelklehr** [comment]
Thank you. Please consider maintaining a CHANGELOG file and using git tags for versions released on npm. Otherwise updating to a new version is a total gamble.
