### ISSUE TITLE
Android: Class referenced in the manifest, SendIntentActivity, was not found

### ISSUE THREAD

**Issue by bchellingworth** [carsten-klaffke/send-intent#76]
**Describe the bug**
When registering the new activity in android manifest, I get an error saying that the SendIntentActivity class cannot be found.

**To Reproduce**
1: Install plugin with npm and run npx cap sync
2: Edit the AndroidManifest.xml to add the new activity directly under the main activity.
3: AndroidStudio highlights the line "android:name="de.mindlib.sendIntent.SendIntentActivity" saying class not found
4: Edit the above line to the correct namespace (in my case com.rewind.app) so "com.rewind.app.SendIntentActivity"
5: AndroidStudio still says class not found, I have tried several variations e.g. com.rewind.sendIntent.SendIntentActivity etc but with no success. If I search my whole project it says there is no class called SendIntentActivity

**Expected behavior**
I would expect the class to be found

**Additional info**
I can still build the prject, but if I then try to share to the app it crashes and I get a similar error about the class not existing.

Is this a bug or am I just missing something? If I am missing something is there an opportunity to update the docs to clarify.

p.s. Thank you for this plugin

**Comment by carsten-klaffke** [comment]
Hello! android:name="de.mindlib.sendIntent.SendIntentActivity" would be the correct configuration. Maybe you have to refresh your project and invalidate caches after you executed "npx cap sync". Does cap sync print "[capacitor]        send-intent@3.0.12"?  Do you see the send-intent Java module in your Android project?

**Comment by bchellingworth** [comment]
Thank you so much for getting back to me.

clearing the cache in android studio fixed the problem. You're a life saver. Thank you.

Also just a little FYI, the example in the repo doesn't seem to match up with the instructions in the readme, perhaps its an out of date example now that you are requiring a new activity for android? Just flagging it.

Thanks again!

**Comment by carsten-klaffke** [comment]
I'm happy to hear that!
Thanks for the info. The example is pretty old and it was added by a contributor. I'll see if can get an update on this soon.
Cheers
